#!/bin/bash
# Rebuild the buildbot master image.
set -ex
set -euo pipefail

# Get script dir since the script could be executed in many different places.
SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
source $SCRIPT_DIR/defaults.sh

cp $(readlink -f $BUILDBOT_CONFIG) $BUILD_TEMPDIR/master.cfg
cat > $BUILD_TEMPDIR/Dockerfile.master <<EOF
FROM ${PROJ_PREFIX}-master-base

# Install treq for HTTPClientService
# Required for some features like GitHub integration
RUN pip3 install treq

COPY master.cfg /var/lib/buildbot/master.cfg

# Run image (copied from parent Dockerfile)
WORKDIR /var/lib/buildbot
CMD ["dumb-init", "/usr/src/buildbot/docker/start_buildbot.sh"]

EOF

cd $BUILD_TEMPDIR
docker build -t "${PROJ_PREFIX}-master" -f Dockerfile.master .
