#!/bin/bash
# Build the buildbot base images.
set -ex
set -euo pipefail

# Get script dir since the script could be executed in many different places.
SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
source $SCRIPT_DIR/defaults.sh

# Work in workdir
cd $EZBB_WORKDIR

# Check out buildbot folder if not present
if [ ! -d "buildbot" ]; then
    git clone https://github.com/buildbot/buildbot.git buildbot
fi

# Check out desired hash
pushd buildbot
git reset --hard $BB_HASH
popd

# Apply patches
#pushd buildbot
#git am -3 $SCRIPT_DIR/patches/*.patch
#popd

# Build buildbot master image
pushd buildbot/master
docker build -t "${PROJ_PREFIX}-master-base" .
popd

# Build buildbot worker image
pushd buildbot/worker
docker build -t "${PROJ_PREFIX}-worker-base" -f ../../Dockerfile.worker .
popd
