builders:
- name: "runtests"
  git_url: "git://github.com/riscv-boom/riscv-boom.git"
  steps:
  - ["build verilator", "echo 'Hello world!'"]
  - ["build the rtl", "echo 'This is!'"]
  - ["run the tests", "echo 'A Test!'"]

workers:
- name: "exampleworker"
  password: "password123456"
- name: "exampleworker1"
  password: "password123456"
- name: "exampleworker2"
  password: "password123456"
