#!/bin/bash
# Re-run the master instance from the master image.
set -ex
set -euo pipefail

# Get script dir since the script could be executed in many different places.
SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
source $SCRIPT_DIR/defaults.sh

# Make sure the sqlite database file exists.
touch $SQLITE_FILE

# Terminate any previous running instance.
docker rm "${PROJ_PREFIX}-master-inst" --force || true

# Usage notes:
# -v a:b = binds host file a to container file b
# -p a:b = bind host port a to container port b
# -d = detach and run in background
# -e "FOO=bar" = set environment variable in container
docker run --name "${PROJ_PREFIX}-master-inst" -it \
  -v "${SQLITE_FILE}:/var/lib/buildbot/state.sqlite" \
  -p $BUILDBOT_ADMIN_PORT:$BUILDBOT_ADMIN_PORT \
  -p $BUILDBOT_COMMS_PORT:$BUILDBOT_COMMS_PORT \
  -e "BUILDBOT_ADMIN_PORT=${BUILDBOT_ADMIN_PORT}" \
  -e "BUILDBOT_COMMS_PORT=${BUILDBOT_COMMS_PORT}" \
  -d \
  "${PROJ_PREFIX}-master"
